name: forennsic
dependencies:
  - python=3.8.10
  - pip=21.1.3
  - pip:
      - tensorflow==2.4.2
      - tensorflow_datasets==4.3.0
      - streamlit==0.84.1
      - scikit-learn==0.24.2
      - fabric==2.6.0
      - matplotlib==3.4.2
      - seaborn==0.11.1
      - numpy~=1.19.5
      - invoke~=1.6.0
      - pandas~=1.2.5
      - python-Levenshtein==0.12.2
      - pyarrow==5.0.0
